### ISSUE TITLE
Omit section on markdown.extension.togglePreview

### ISSUE THREAD

**Issue by WesleyMConner** [FredHappyface/VSCode.OSKeybindings#2]
This is less of a bug and more of a tweak to mirror the change mentioned here:
[command 'markdown.extension.togglePreview' not found #321](https://github.com/yzhang-gh/vscode-markdown/commit/05fb1af27150fa8c1c271fc03533d28787ea25d1). Per this posting, **togglePreviewToSide** appears to have been revised/retired.

I was getting the error message "_command 'markdown.extension.togglePreview' not found_". The fix was to drop one small section in your keybindings.json tweaks. Specifically, I dropped:

```json
        {
		"command": "markdown.extension.togglePreview",
		"key": "ctrl+shift+v",
		"mac": "cmd+shift+v",
		"when": "!terminalFocus"
	},
```

I am now able to do both toggle (ctrl-shift-V) and open preview to side (ctrl-k v) on my iMac running macOS Big Sur without issue.

**Comment by FredHappyface** [comment]
Thanks for the suggestion! I'll aim to update the Windows and Linux versions sometime in the near future and implement this fix 🙂

**Comment by FredHappyface** [comment]
Updated. And I've also updated Linux and Windows keybindings to 1.52 😊
