### ISSUE TITLE
Bug: Key conflicts with the Vim plugin

### ISSUE THREAD

**Issue by zenpk** [FredHappyface/VSCode.OSKeybindings#9]
# Bug: Key conflicts with the Vim plugin

## Issue Details

There are some key conflicts with the Vim plugin, mainly in Vim's search bar (`/`).

1. When searching, all arrow keys are not working. Expected: Left-right to navigate the search text, up-down to navigate the search history. Actual: The arrow keys control the cursor.
2. Backspace deletes code instead of the search text.

### Description

I believe there are more conflicts but I can't remember them all. I have stopped using this plugin because macOS has trained me not to do anything but just accept whatever they want me to do (sadly). But still, I want to share this information because it took me a while to find out which plugin was causing the issue. It would be nice to inform other users in README or somewhere. 

### System Information

I was using the WindowsKeybindings on both Windows and macOS

**Comment by FredHappyface** [comment]
Hi thanks for the issue. Unfortunately all this plugin can do is add to the existing keybindings. Unfortunately this can cause wonky behaviour and conflicts with other plugins (often as these also add new keybindings). Sometimes this may get fixed as new versions are released but this isn't a guarentee (the current version is '1.92.1')

Sorry I couldn't be more helpful on this one :(

**Comment by zenpk** [comment]
Hi @FredHappyface , thanks for the reply! I totally understand that this could be hard to fix. What I'm suggesting is adding this information to the readme so that people can know the cause and fix the issues themselves. I've made a PR #10 for it. Please feel free to merge it or close it!

**Comment by FredHappyface** [comment]
Thanks so much for that! I'll take a look now. Just as an fyi, I've learned that there is another similar extention to this one that may be worth checking out, a quick glimpse looks really promising but I'm yet to try it out myself: https://marketplace.visualstudio.com/items?itemName=jbro.vscode-default-keybindings
